"""MITRE ATT&CK Navigator layer export (coverage matrix → shareable JSON).

The webapp's Coverage page is a hand-rolled matrix; this service renders the
*same* `RULE_META` registry into the official Navigator layer format so an
analyst can drop it into https://mitre-attack.github.io/attack-navigator/
(Upload a layer → local file) and see OutPost's coverage in the tool the
detection-engineering world actually uses.

Layer semantics kept deliberately simple and honest:

- one `techniques` entry per (technique ID, tactic) pair — rules that map to
  the same technique cell (e.g. first-seen-process and attack-chain both on
  T1204/Execution) merge into one cell so Navigator never paints twice;
- `score` = the heaviest rule weight in the merged cell (Navigator sizes
  cells by score);
- `color` = the worst severity among the merged rules (malicious wins) so the
  layer's heat carries the same meaning as the webapp chips;
- `comment` lists every merged rule_id + rule_name, so a hover in Navigator
  identifies the exact rules, not just the technique.
"""

from typing import Any

from .risk import RULE_META, rule_name


def _tactic_slug(display: str) -> str:
    """Display name → Navigator tactic slug. Every Enterprise tactic follows
    lowercase-hyphen form ("Command and Control" → "command-and-control"), so
    deriving beats maintaining a dict that could drift out of sync."""
    return display.lower().replace(" ", "-")


# The canonical MITRE ATT&CK Enterprise tactic set (v14+). The verify.sh
# coverage gate and its pytest sibling assert the Navigator layer covers every
# one of these — a tactic with no rule fails the sweep, so the "coverage story"
# is enforced by CI, not just told on the Coverage page.
ENTERPRISE_TACTICS_14 = [
    "reconnaissance",
    "resource-development",
    "initial-access",
    "execution",
    "persistence",
    "privilege-escalation",
    "defense-evasion",
    "credential-access",
    "discovery",
    "lateral-movement",
    "collection",
    "command-and-control",
    "exfiltration",
    "impact",
]

# Same severity tone the webapp chips use, as Navigator hex colors.
SEVERITY_COLORS = {
    "malicious": "#c4453b",
    "suspicious": "#d9a441",
}

GRADIENT_MAX = max(m["weight"] for m in RULE_META.values())


def tactic_coverage() -> tuple[int, int]:
    """(covered, total) of the canonical Enterprise tactic set, read from the
    actual Navigator layer output (not from RULE_META directly) — so the badge,
    the layer, and the Coverage page can never disagree about the story.
    """
    layer = build_navigator_layer()
    covered = {cell["tactic"] for cell in layer["techniques"]} & set(ENTERPRISE_TACTICS_14)
    return len(covered), len(ENTERPRISE_TACTICS_14)


def build_navigator_layer() -> dict[str, Any]:
    """A Navigator v4.3 layer covering every rule in RULE_META."""
    merged: dict[tuple[str, str], dict[str, Any]] = {}
    for rule_id, meta in sorted(RULE_META.items()):
        slug = _tactic_slug(meta["tactic"])
        key = (meta["technique"], slug)
        cell = merged.setdefault(
            key,
            {"techniqueID": meta["technique"], "tactic": slug, "score": 0, "color": "#d9a441", "comment": ""},
        )
        cell["score"] = max(cell["score"], meta["weight"])
        if meta["severity"] == "malicious":
            cell["color"] = SEVERITY_COLORS["malicious"]
        cell["comment"] = (cell["comment"] + ", " if cell["comment"] else "") + rule_id

    techniques = [merged[k] for k in sorted(merged)]
    for cell in techniques:
        cell["comment"] = "; ".join(
            f"{rid} ({rule_name(rid)})" for rid in cell["comment"].split(", ")
        )

    return {
        "version": "4.3",
        "name": "OutPost detection coverage",
        "description": (
            f"{len(RULE_META)} detection rules merged into {len(techniques)} ATT&CK technique cells "
            f"across {len({t['tactic'] for t in techniques})} tactics — MITRE ATT&CK Enterprise. "
            "Score is the heaviest rule's risk weight; color is the worst fired severity "
            "(red = malicious, amber = suspicious). Generated by OutPost."
        ),
        "domain": "enterprise-attack",
        "techniques": techniques,
        "gradient": {
            "colors": ["#3a3d45", "#d9a441", "#c4453b"],
            "min": 0,
            "max": GRADIENT_MAX,
        },
        "legendItems": [
            {"label": "malicious-severity rule", "color": "#c4453b"},
            {"label": "suspicious-severity rule", "color": "#d9a441"},
        ],
        "showTacticRowBackground": False,
        "tacticRowBackground": "#1c1e24",
        "selectTechniquesAcrossTactics": True,
    }
