"""Auto-generated Suricata/Sigma rules from a run's findings.

Phase 6 Task 27 — docs/10-STANDOUT-FEATURES.md #8. Template-based, not ML:
a naive but *correct* rule is more valuable than an ambitious one that
doesn't compile. One Suricata rule per malicious connection; one Sigma rule
per distinct alert rule_id.

Sigma note: `|contains`/`|endswith` are literal substring matches, NOT regex
— so patterns are plain literals here (never re.escape'd).
"""

import hashlib
import uuid


def _stable_sid(seed: str) -> int:
    """Deterministic, process-independent rule sid (builtin hash() is salted)."""
    digest = int(hashlib.sha1(seed.encode("utf-8")).hexdigest(), 16)
    return 100_000 + (digest % 900_000)


# ---------------------------------------------------------------------------
# Suricata — one rule per malicious connection (network-based detection)
# ---------------------------------------------------------------------------
def generate_suricata_rules(run_id: str, connections: list[dict]) -> list[str]:
    rules: list[str] = []
    for conn in connections:
        if conn.get("reputation") != "malicious":
            continue
        ip = conn["dest_ip"]
        port = conn.get("dest_port") or "any"
        proto = (conn.get("protocol") or "tcp").lower()
        sid = _stable_sid(f"{run_id}:{ip}:{port}")
        rules.append(
            f"alert {proto} any any -> {ip} {port} "
            f'(msg:"OutPost: possible C2 traffic observed in run {run_id} to {ip}"; '
            f'sid:{sid}; rev:1;)'
        )
    return rules


# ---------------------------------------------------------------------------
# Sigma — one rule per distinct alert type (log-based detection)
# ---------------------------------------------------------------------------
# rule_id -> (title, logsource category, detection field, modifier, literal pattern)
_SIGMA_TEMPLATES: dict[str, dict] = {
    "lolbin-abuse": {
        "title": "OutPost: LOLBin abuse observed in run {run_id}",
        "logsource": "process_creation",
        "field": "CommandLine",
        "modifier": "contains",
        "pattern": "-enc",  # matches both `-enc` and `-encodedcommand`
        "level": "high",
    },
    "suspicious-parent-child": {
        "title": "OutPost: suspicious parent-child relationship in run {run_id}",
        "logsource": "process_creation",
        "field": "ParentImage",
        "modifier": "endswith",
        "pattern": "winword.exe",
        "level": "high",
    },
    "masquerading": {
        "title": "OutPost: possible process masquerading in run {run_id}",
        "logsource": "process_creation",
        "field": "Image",
        "modifier": "endswith",
        "pattern": "svchost.exe",
        "level": "medium",
    },
    "registry-persistence": {
        "title": "OutPost: registry Run-key persistence in run {run_id}",
        "logsource": "registry_set",
        "field": "TargetObject",
        "modifier": "contains",
        "pattern": r"\CurrentVersion\Run",
        "level": "medium",
    },
}


def generate_sigma_rules(run_id: str, alerts: list[dict]) -> list[str]:
    """One Sigma rule per distinct alert rule_id (deduplicated)."""
    rules: list[str] = []
    seen: set[str] = set()
    for alert in alerts:
        rule_id = alert.get("rule_id")
        if not rule_id or rule_id in seen:
            continue
        seen.add(rule_id)
        tmpl = _SIGMA_TEMPLATES.get(rule_id)
        if not tmpl:
            continue
        rules.append(
            f"title: {tmpl['title'].format(run_id=run_id)}\n"
            f"id: {uuid.uuid4()}\n"
            f"status: experimental\n"
            f"description: Generated by OutPost from observed behavior (docs/10 #8)\n"
            f"logsource:\n"
            f"    category: {tmpl['logsource']}\n"
            f"    product: windows\n"
            f"detection:\n"
            f"    selection:\n"
            f"        {tmpl['field']}|{tmpl['modifier']}: '{tmpl['pattern']}'\n"
            f"    condition: selection\n"
            f"level: {tmpl['level']}\n"
        )
    return rules
